name: CI

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  # Allow to trigger this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  macos:
    uses: ./.github/workflows/macos.yml
